name: Unzip and Build Z-eye

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Extract Project ZIP
      run: |
        if [ -f "z-eye.zip" ]; then
          unzip -o z-eye.zip
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install --force

    - name: Build Web App
      run: npx vite build
